name: Deploy to Cloudflare

on: push

jobs:
  deploy-to-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
        run: bun install --frozen-lockfile
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: --config wrangler.toml deploy
